/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as SplatRouteImport } from './routes/$'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as PlatformUsageRouteImport } from './routes/_platform/usage'
import { Route as PlatformProfileRouteImport } from './routes/_platform/profile'
import { Route as PlatformDomainsRouteImport } from './routes/_platform/domains'
import { Route as PlatformDashboardRouteImport } from './routes/_platform/dashboard'
import { Route as PlatformBillingRouteImport } from './routes/_platform/billing'
import { Route as PlatformAppRouteImport } from './routes/_platform/app'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingMissionRouteImport } from './routes/_marketing/mission'
import { Route as MarketingDocsRouteImport } from './routes/_marketing/docs'
import { Route as MarketingChangelogRouteImport } from './routes/_marketing/changelog'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsageRoute = PlatformUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformProfileRoute = PlatformProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDomainsRoute = PlatformDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformBillingRoute = PlatformBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAppRoute = PlatformAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => PlatformRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingMissionRoute = MarketingMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDocsRoute = MarketingDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChangelogRoute = MarketingChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/changelog': typeof MarketingChangelogRoute
  '/docs': typeof MarketingDocsRoute
  '/mission': typeof MarketingMissionRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/app': typeof PlatformAppRoute
  '/billing': typeof PlatformBillingRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/domains': typeof PlatformDomainsRoute
  '/profile': typeof PlatformProfileRoute
  '/usage': typeof PlatformUsageRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/changelog': typeof MarketingChangelogRoute
  '/docs': typeof MarketingDocsRoute
  '/mission': typeof MarketingMissionRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/app': typeof PlatformAppRoute
  '/billing': typeof PlatformBillingRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/domains': typeof PlatformDomainsRoute
  '/profile': typeof PlatformProfileRoute
  '/usage': typeof PlatformUsageRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_marketing/changelog': typeof MarketingChangelogRoute
  '/_marketing/docs': typeof MarketingDocsRoute
  '/_marketing/mission': typeof MarketingMissionRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_platform/app': typeof PlatformAppRoute
  '/_platform/billing': typeof PlatformBillingRoute
  '/_platform/dashboard': typeof PlatformDashboardRoute
  '/_platform/domains': typeof PlatformDomainsRoute
  '/_platform/profile': typeof PlatformProfileRoute
  '/_platform/usage': typeof PlatformUsageRoute
  '/api/$': typeof ApiSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/editor'
    | '/login'
    | '/register'
    | '/changelog'
    | '/docs'
    | '/mission'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/billing'
    | '/dashboard'
    | '/domains'
    | '/profile'
    | '/usage'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/editor'
    | '/login'
    | '/register'
    | '/changelog'
    | '/docs'
    | '/mission'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/billing'
    | '/dashboard'
    | '/domains'
    | '/profile'
    | '/usage'
    | '/api/$'
  id:
    | '__root__'
    | '/$'
    | '/_marketing'
    | '/_platform'
    | '/editor'
    | '/login'
    | '/register'
    | '/_marketing/changelog'
    | '/_marketing/docs'
    | '/_marketing/mission'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/_marketing/terms'
    | '/_platform/app'
    | '/_platform/billing'
    | '/_platform/dashboard'
    | '/_platform/domains'
    | '/_platform/profile'
    | '/_platform/usage'
    | '/api/$'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/usage': {
      id: '/_platform/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof PlatformUsageRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/profile': {
      id: '/_platform/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PlatformProfileRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/domains': {
      id: '/_platform/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof PlatformDomainsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/dashboard': {
      id: '/_platform/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/billing': {
      id: '/_platform/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof PlatformBillingRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/app': {
      id: '/_platform/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof PlatformAppRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/mission': {
      id: '/_marketing/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MarketingMissionRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/docs': {
      id: '/_marketing/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MarketingDocsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/changelog': {
      id: '/_marketing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof MarketingChangelogRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingChangelogRoute: typeof MarketingChangelogRoute
  MarketingDocsRoute: typeof MarketingDocsRoute
  MarketingMissionRoute: typeof MarketingMissionRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingChangelogRoute: MarketingChangelogRoute,
  MarketingDocsRoute: MarketingDocsRoute,
  MarketingMissionRoute: MarketingMissionRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PlatformRouteChildren {
  PlatformAppRoute: typeof PlatformAppRoute
  PlatformBillingRoute: typeof PlatformBillingRoute
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformDomainsRoute: typeof PlatformDomainsRoute
  PlatformProfileRoute: typeof PlatformProfileRoute
  PlatformUsageRoute: typeof PlatformUsageRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAppRoute: PlatformAppRoute,
  PlatformBillingRoute: PlatformBillingRoute,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformDomainsRoute: PlatformDomainsRoute,
  PlatformProfileRoute: PlatformProfileRoute,
  PlatformUsageRoute: PlatformUsageRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  MarketingRoute: MarketingRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
